<?php
/**
 * @var $block \Magentiz\ConfigFinder\Block\Widget\Select
 */
?>
<?= $block->getBeforeHtml() ?>
<select <?= /* @noEscape */ $block->getAttributesHtml(), $block->getUiId() ?>>
    <?php foreach ($block->_getOptions() as $option) : ?>
    	<?php if(is_array($option['value'])): ?>
            <optgroup label='<?= $option["label"]; ?>'>
                <?php foreach ($option['value'] as $subOption): ?>
                   <?=  $block->_renderOption($subOption) ?>
                <?php endforeach; ?>
            </optgroup>
       	<?php else: ?>
            <?= $block->_renderOption($option); ?>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
<?= $block->getAfterHtml() ?>
